### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [lcserny/go-videosmover#18]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by lcserny** [comment]
Hello, yes I am interested! If you have spare time to make a logo, that would be very much appreciated. Keep in mind though that I plan to make this project into a bigger video management software as I will add more features to it.
Also let me know how you want me to mention you on the readme and license.

Thanks a lot, have a nice day!

**Comment by zuurw** [comment]
Hi, I would like to know what do you want for this logo, can you give me something to get inspired?

Thank you!

Best Regards!

**Comment by lcserny** [comment]
Hello, well, I am not strict about it, so you can do whatever you think best suits the project.
But since you asked, maybe I can point you towards a direction:
- since this is mainly a Kodi / XBMC helper, maybe something similar to Kodi
- also, since this is going towards a video manager, maybe something related to videos, play/pause buttons, film rolls and such
- I like clean simple designs way more than complicated ones
- I would go for 2, max 3 pastel colors (can be only one or black and white if you like), I tend to not like too many colors in something, it distracts too much
- i like colors to fade cleanly and flat material design also, pls no over-the-top 3D effects
- it might be a bit to much to ask but maybe something that stands out and is recognizable at different sizes also (cause some logos, if you show them in 20x20px let's say, they are not recognizable)

That's about it I think, thanks a lot!

**Comment by zuurw** [comment]
Hi @lcserny 

I create some design for this project, first I create 2 logos with the letter G and the player button, then I create 2 more logos with the player button and I get inspired in the kodi logo. The last logos that I create are inspired in the play and pause buttons.

See if you like one of this logos, if not I can make other one.

Greetings!

![govideos](https://user-images.githubusercontent.com/40801473/58642636-a5192e00-82f5-11e9-8af4-99c1a1628e75.jpg)

**Comment by lcserny** [comment]
Hello, thanks for the suggestions.
I do however think these do not align exactly with what I had in mind, maybe you can get inspired from some of the logos here: https://www.graphicsprings.com/logo-maker in the "Entertainment and the Arts" category maybe?
I will post below some examples I like:
![Screenshot from 2019-06-03 14-18-53](https://user-images.githubusercontent.com/11813849/58798401-2da41100-860b-11e9-8350-95dc1b3ee627.png)
![Screenshot from 2019-06-03 14-19-16](https://user-images.githubusercontent.com/11813849/58798405-309f0180-860b-11e9-987c-636882b6b476.png)
![Screenshot from 2019-06-03 14-19-35](https://user-images.githubusercontent.com/11813849/58798407-33015b80-860b-11e9-8032-e2f1540c7212.png)
![Screenshot from 2019-06-03 14-19-46](https://user-images.githubusercontent.com/11813849/58798411-35fc4c00-860b-11e9-846d-493f90c18b6a.png)
![Screenshot from 2019-06-03 14-20-15](https://user-images.githubusercontent.com/11813849/58798414-38f73c80-860b-11e9-983b-38e9849913c4.png)
![Screenshot from 2019-06-03 14-20-34](https://user-images.githubusercontent.com/11813849/58798420-3b599680-860b-11e9-8ccb-e102aab07cc9.png)
![Screenshot from 2019-06-03 14-21-30](https://user-images.githubusercontent.com/11813849/58798436-3dbbf080-860b-11e9-9fe4-afbdfb8f69dd.png)
![Screenshot from 2019-06-03 14-22-04](https://user-images.githubusercontent.com/11813849/58798441-3f85b400-860b-11e9-8355-d7d546aaeec5.png)

Here are some more icons I really like: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
Thanks a lot, I can't wait to see what you come up with!

**Comment by lcserny** [comment]
Hello @zuurw , any updates?

**Comment by lcserny** [comment]
Logo created.
